import OpenAI from "openai";
import { buildSummaryPrompt } from "./types.js";
import type { AIProvider } from "./types.js";

export class DeepSeekProvider implements AIProvider {
  private client: OpenAI | undefined;

  private getClient() {
    const apiKey = process.env.DEEPSEEK_API_KEY;

    if (!apiKey) {
      throw new Error(
        "Missing DEEPSEEK_API_KEY. Set it in your environment or in a .env file."
      );
    }

    if (!this.client) {
      this.client = new OpenAI({
        apiKey,
        baseURL: process.env.DEEPSEEK_BASE_URL ?? "https://api.deepseek.com/v1",
      });
    }

    return this.client;
  }

  async transcribeAudio(_filePath: string): Promise<string> {
    throw new Error(
      "Transcription is not supported with AI_PROVIDER=deepseek in this app. Use AI_PROVIDER=openai for audio transcription."
    );
  }

  async generateSummary(transcript: string, translate: boolean) {
    const client = this.getClient();
    const model = process.env.DEEPSEEK_SUMMARY_MODEL ?? "deepseek-chat";
    const prompt = buildSummaryPrompt(transcript, translate);

    const response = await client.chat.completions.create({
      model,
      messages: [{ role: "user", content: prompt }],
      temperature: 0.3,
    });

    const content = response.choices?.[0]?.message?.content;

    if (!content) {
      throw new Error("No summary generated by the model.");
    }

    return content;
  }
}
