import fs from "fs";
import OpenAI from "openai";
import { buildSummaryPrompt } from "./types.js";
import type { AIProvider } from "./types.js";

export class OpenAIProvider implements AIProvider {
  private client: OpenAI | undefined;

  private getClient() {
    const apiKey = process.env.OPENAI_API_KEY;

    if (!apiKey) {
      throw new Error(
        "Missing OPENAI_API_KEY. Set it in your environment or in a .env file."
      );
    }

    if (!this.client) {
      this.client = new OpenAI({ apiKey });
    }

    return this.client;
  }

  async transcribeAudio(filePath: string) {
    const client = this.getClient();
    const model = process.env.OPENAI_TRANSCRIPTION_MODEL ?? "gpt-4o-transcribe";

    const transcription = await client.audio.transcriptions.create({
      file: fs.createReadStream(filePath),
      model,
    });

    return transcription.text;
  }

  async generateSummary(transcript: string, translate: boolean) {
    const client = this.getClient();
    const model = process.env.OPENAI_SUMMARY_MODEL ?? "gpt-4o";
    const prompt = buildSummaryPrompt(transcript, translate);

    const response = await client.chat.completions.create({
      model,
      messages: [{ role: "user", content: prompt }],
      temperature: 0.3,
    });

    const content = response.choices?.[0]?.message?.content;

    if (!content) {
      throw new Error("No summary generated by the model.");
    }

    return content;
  }
}
