import fs from 'node:fs';
import { execFile } from 'node:child_process';
import { tmpdir } from 'node:os';
import { extname, join } from 'node:path';
import { promisify } from 'node:util';
import OpenAI from 'openai';
import { buildSummaryPrompt, getTranslationTargetLanguage } from './types';
import type { AIProvider } from './types';

type TranscriptionResponseFormat = 'verbose_json' | 'json' | 'text';
const execFileAsync = promisify(execFile);

export class OpenAIProvider implements AIProvider {
  private client: OpenAI | undefined;

  private getClient() {
    const apiKey = process.env.OPENAI_API_KEY;

    if (!apiKey) {
      throw new Error('Missing OPENAI_API_KEY. Set it in your environment or in a .env file.');
    }

    if (!this.client) {
      this.client = new OpenAI({ apiKey });
    }

    return this.client;
  }

  async transcribeAudio(filePath: string) {
    const client = this.getClient();
    const model = process.env.OPENAI_TRANSCRIPTION_MODEL ?? 'gpt-4o-transcribe';
    const formats: TranscriptionResponseFormat[] = ['verbose_json', 'json', 'text'];
    const modelMaxSeconds = this.getModelMaxDurationSeconds();

    const durationSeconds = await this.getDurationSeconds(filePath);
    if (durationSeconds && durationSeconds > modelMaxSeconds) {
      return this.transcribeFromChunks(client, filePath, model, formats, modelMaxSeconds);
    }

    try {
      const transcription = await this.transcribeWithFormats(client, filePath, model, formats);
      return this.buildTranscriptionResult(client, transcription);
    } catch (error) {
      const maxDurationSeconds = this.extractMaxDurationSeconds(error);

      if (!maxDurationSeconds) {
        throw this.toError(error);
      }

      return this.transcribeFromChunks(client, filePath, model, formats, maxDurationSeconds);
    }
  }

  async generateSummaries(transcript: string, detectedLanguage: string) {
    const client = this.getClient();
    const model = process.env.OPENAI_SUMMARY_MODEL ?? 'gpt-4o';
    const translationTargetLanguage = getTranslationTargetLanguage(detectedLanguage);

    const summaryInDetectedLanguage = await this.generateSingleSummary(
      client,
      model,
      buildSummaryPrompt(transcript, detectedLanguage, detectedLanguage),
    );

    const summaryInEnglish = await this.generateSingleSummary(
      client,
      model,
      buildSummaryPrompt(transcript, detectedLanguage, translationTargetLanguage),
    );

    return {
      summaryInDetectedLanguage,
      summaryInEnglish,
    };
  }

  private async generateSingleSummary(client: OpenAI, model: string, prompt: string) {
    const response = await client.chat.completions.create({
      model,
      messages: [{ role: 'user', content: prompt }],
      temperature: 0.3,
    });

    const content = response.choices?.[0]?.message?.content;

    if (!content) {
      throw new Error('No summary generated by the model.');
    }

    return content;
  }

  private extractTranscript(transcription: unknown): string {
    if (typeof transcription === 'string') {
      return transcription;
    }

    if (
      typeof transcription === 'object' &&
      transcription !== null &&
      'text' in transcription &&
      typeof transcription.text === 'string'
    ) {
      return transcription.text;
    }

    return '';
  }

  private extractLanguage(transcription: unknown): string | undefined {
    if (
      typeof transcription === 'object' &&
      transcription !== null &&
      'language' in transcription &&
      typeof transcription.language === 'string' &&
      transcription.language.trim()
    ) {
      return transcription.language.trim();
    }

    return undefined;
  }

  private getModelMaxDurationSeconds() {
    const configured = Number(process.env.OPENAI_TRANSCRIPTION_MODEL_MAX_SECONDS);
    if (Number.isFinite(configured) && configured > 0) {
      return configured;
    }

    return 1400;
  }

  private async getDurationSeconds(filePath: string): Promise<number | undefined> {
    try {
      const { stdout } = await execFileAsync('ffprobe', [
        '-v',
        'error',
        '-show_entries',
        'format=duration',
        '-of',
        'default=noprint_wrappers=1:nokey=1',
        filePath,
      ]);

      const value = parseFloat(String(stdout).trim());
      return Number.isFinite(value) && value > 0 ? value : undefined;
    } catch (error) {
      // If ffprobe is unavailable, fall back to API-based duration enforcement
      if (
        typeof error === 'object' &&
        error !== null &&
        'code' in error &&
        (error as { code?: string }).code === 'ENOENT'
      ) {
        return undefined;
      }

      return undefined;
    }
  }

  private async transcribeWithFormats(
    client: OpenAI,
    filePath: string,
    model: string,
    formats: TranscriptionResponseFormat[],
  ) {
    let lastError: unknown;

    for (const responseFormat of formats) {
      try {
        return await client.audio.transcriptions.create({
          file: fs.createReadStream(filePath),
          model,
          response_format: responseFormat,
        });
      } catch (error) {
        lastError = error;
      }
    }

    throw this.toError(lastError);
  }

  private async transcribeFromChunks(
    client: OpenAI,
    filePath: string,
    model: string,
    formats: TranscriptionResponseFormat[],
    maxDurationSeconds: number,
  ) {
    const { chunkDir, chunkFiles } = await this.splitAudioForTranscription(filePath, maxDurationSeconds);

    try {
      const chunkTranscripts: string[] = [];
      let detectedLanguageFromChunks: string | undefined;

      for (const chunkFilePath of chunkFiles) {
        const chunkTranscription = await this.transcribeWithFormats(client, chunkFilePath, model, formats);
        const chunkTranscript = this.extractTranscript(chunkTranscription).trim();

        if (chunkTranscript) {
          chunkTranscripts.push(chunkTranscript);
        }

        const chunkLanguage = this.extractLanguage(chunkTranscription);
        if (
          !detectedLanguageFromChunks &&
          chunkLanguage &&
          chunkLanguage.toLowerCase() !== 'unknown'
        ) {
          detectedLanguageFromChunks = chunkLanguage;
        }
      }

      const transcript = chunkTranscripts.join('\n\n').trim();

      if (!transcript) {
        throw new Error('No transcript text returned by the transcription model.');
      }

      const detectedLanguage =
        detectedLanguageFromChunks ?? (await this.detectLanguageFromTranscript(client, transcript));

      return {
        transcript,
        detectedLanguage,
      };
    } finally {
      fs.rmSync(chunkDir, { recursive: true, force: true });
    }
  }

  private async buildTranscriptionResult(client: OpenAI, transcription: unknown) {
    const transcript = this.extractTranscript(transcription);

    if (!transcript.trim()) {
      throw new Error('No transcript text returned by the transcription model.');
    }

    const maybeLanguage = this.extractLanguage(transcription);
    const detectedLanguage =
      maybeLanguage && maybeLanguage !== 'unknown'
        ? maybeLanguage
        : await this.detectLanguageFromTranscript(client, transcript);

    return {
      transcript,
      detectedLanguage,
    };
  }

  private extractMaxDurationSeconds(error: unknown): number | undefined {
    if (!(error instanceof Error)) {
      return undefined;
    }

    const message = error.message.toLowerCase();

    if (!message.includes('maximum') || !message.includes('seconds')) {
      return undefined;
    }

    const matches = [...message.matchAll(/([0-9]+(?:\.[0-9]+)?)\s*seconds/gi)];
    if (matches.length === 0) {
      return undefined;
    }

    const parsed = Number(matches[matches.length - 1][1]);
    return Number.isFinite(parsed) && parsed > 0 ? parsed : undefined;
  }

  private async splitAudioForTranscription(filePath: string, maxDurationSeconds: number) {
    const chunkDurationSeconds = this.resolveChunkDurationSeconds(maxDurationSeconds);
    const chunkDir = fs.mkdtempSync(join(tmpdir(), 'meeting-assistant-audio-chunks-'));
    const extension = extname(filePath) || '.webm';
    const outputPattern = join(chunkDir, `chunk-%03d${extension}`);

    try {
      await execFileAsync('ffmpeg', [
        '-hide_banner',
        '-loglevel',
        'error',
        '-i',
        filePath,
        '-f',
        'segment',
        '-segment_time',
        String(chunkDurationSeconds),
        '-c',
        'copy',
        outputPattern,
      ]);
    } catch (error) {
      fs.rmSync(chunkDir, { recursive: true, force: true });

      if (
        typeof error === 'object' &&
        error !== null &&
        'code' in error &&
        error.code === 'ENOENT'
      ) {
        throw new Error(
          'Audio is longer than the model limit and ffmpeg is not installed. Install ffmpeg or send shorter audio files.',
        );
      }

      throw new Error(`Failed to split large audio file for transcription. ${this.toError(error).message}`);
    }

    const chunkFiles = fs
      .readdirSync(chunkDir)
      .sort((a, b) => a.localeCompare(b))
      .map((name) => join(chunkDir, name))
      .filter((chunkPath) => fs.statSync(chunkPath).isFile());

    if (chunkFiles.length === 0) {
      fs.rmSync(chunkDir, { recursive: true, force: true });
      throw new Error('Failed to split audio into chunks for transcription.');
    }

    return { chunkDir, chunkFiles };
  }

  private resolveChunkDurationSeconds(maxDurationSeconds: number) {
    const configuredChunkSeconds = Number(process.env.OPENAI_TRANSCRIPTION_CHUNK_SECONDS);
    if (
      Number.isFinite(configuredChunkSeconds) &&
      configuredChunkSeconds > 0 &&
      configuredChunkSeconds < maxDurationSeconds
    ) {
      return Math.floor(configuredChunkSeconds);
    }

    return Math.max(60, Math.floor(maxDurationSeconds * 0.85));
  }

  private toError(error: unknown) {
    if (error instanceof Error) {
      return error;
    }

    return new Error('Unable to transcribe audio with any supported response format.');
  }

  private async detectLanguageFromTranscript(client: OpenAI, transcript: string) {
    const model = process.env.OPENAI_LANGUAGE_MODEL ?? process.env.OPENAI_SUMMARY_MODEL ?? 'gpt-4o-mini';
    const prompt = `Identify the main spoken language of the following transcript.
Return only a lowercase ISO 639-1 code (examples: en, pt, es, fr).
If uncertain, return "unknown".

Transcript:
${transcript.slice(0, 5000)}`;

    const response = await client.chat.completions.create({
      model,
      temperature: 0,
      messages: [{ role: 'user', content: prompt }],
    });

    const content = response.choices?.[0]?.message?.content?.trim().toLowerCase();

    if (!content) {
      return 'unknown';
    }

    const languageCode = content.match(/^[a-z]{2,3}$/)?.[0];
    return languageCode ?? 'unknown';
  }
}
