import fs from 'node:fs';
import OpenAI from 'openai';
import { buildSummaryPrompt, getTranslationTargetLanguage } from './types';
import type { AIProvider } from './types';

type TranscriptionResponseFormat = 'verbose_json' | 'json' | 'text';

export class OpenAIProvider implements AIProvider {
  private client: OpenAI | undefined;

  private getClient() {
    const apiKey = process.env.OPENAI_API_KEY;

    if (!apiKey) {
      throw new Error('Missing OPENAI_API_KEY. Set it in your environment or in a .env file.');
    }

    if (!this.client) {
      this.client = new OpenAI({ apiKey });
    }

    return this.client;
  }

  async transcribeAudio(filePath: string) {
    const client = this.getClient();
    const model = process.env.OPENAI_TRANSCRIPTION_MODEL ?? 'gpt-4o-transcribe';
    const formats: TranscriptionResponseFormat[] = ['verbose_json', 'json', 'text'];

    let lastError: unknown;

    for (const responseFormat of formats) {
      try {
        const transcription = await client.audio.transcriptions.create({
          file: fs.createReadStream(filePath),
          model,
          response_format: responseFormat,
        });

        const transcript = this.extractTranscript(transcription);

        if (!transcript.trim()) {
          throw new Error('No transcript text returned by the transcription model.');
        }

        const maybeLanguage = this.extractLanguage(transcription);
        const detectedLanguage =
          maybeLanguage && maybeLanguage !== 'unknown'
            ? maybeLanguage
            : await this.detectLanguageFromTranscript(client, transcript);

        return {
          transcript,
          detectedLanguage,
        };
      } catch (error) {
        lastError = error;
      }
    }

    const message =
      lastError instanceof Error
        ? lastError.message
        : 'Unable to transcribe audio with any supported response format.';
    throw new Error(message);
  }

  async generateSummaries(transcript: string, detectedLanguage: string) {
    const client = this.getClient();
    const model = process.env.OPENAI_SUMMARY_MODEL ?? 'gpt-4o';
    const translationTargetLanguage = getTranslationTargetLanguage(detectedLanguage);

    const summaryInDetectedLanguage = await this.generateSingleSummary(
      client,
      model,
      buildSummaryPrompt(transcript, detectedLanguage, detectedLanguage),
    );

    const summaryInEnglish = await this.generateSingleSummary(
      client,
      model,
      buildSummaryPrompt(transcript, detectedLanguage, translationTargetLanguage),
    );

    return {
      summaryInDetectedLanguage,
      summaryInEnglish,
    };
  }

  private async generateSingleSummary(client: OpenAI, model: string, prompt: string) {
    const response = await client.chat.completions.create({
      model,
      messages: [{ role: 'user', content: prompt }],
      temperature: 0.3,
    });

    const content = response.choices?.[0]?.message?.content;

    if (!content) {
      throw new Error('No summary generated by the model.');
    }

    return content;
  }

  private extractTranscript(transcription: unknown): string {
    if (typeof transcription === 'string') {
      return transcription;
    }

    if (
      typeof transcription === 'object' &&
      transcription !== null &&
      'text' in transcription &&
      typeof transcription.text === 'string'
    ) {
      return transcription.text;
    }

    return '';
  }

  private extractLanguage(transcription: unknown): string | undefined {
    if (
      typeof transcription === 'object' &&
      transcription !== null &&
      'language' in transcription &&
      typeof transcription.language === 'string' &&
      transcription.language.trim()
    ) {
      return transcription.language.trim();
    }

    return undefined;
  }

  private async detectLanguageFromTranscript(client: OpenAI, transcript: string) {
    const model = process.env.OPENAI_LANGUAGE_MODEL ?? process.env.OPENAI_SUMMARY_MODEL ?? 'gpt-4o-mini';
    const prompt = `Identify the main spoken language of the following transcript.
Return only a lowercase ISO 639-1 code (examples: en, pt, es, fr).
If uncertain, return "unknown".

Transcript:
${transcript.slice(0, 5000)}`;

    const response = await client.chat.completions.create({
      model,
      temperature: 0,
      messages: [{ role: 'user', content: prompt }],
    });

    const content = response.choices?.[0]?.message?.content?.trim().toLowerCase();

    if (!content) {
      return 'unknown';
    }

    const languageCode = content.match(/^[a-z]{2,3}$/)?.[0];
    return languageCode ?? 'unknown';
  }
}
